# Generated by Django 5.2.11 on 2026-02-20 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('join_date', models.DateField(auto_now_add=True, verbose_name='Fecha de alta')),
                ('goal', models.CharField(choices=[('weight_loss', 'Pérdida de peso'), ('muscle_gain', 'Ganancia muscular'), ('endurance', 'Resistencia'), ('general', 'Fitness general')], default='general', max_length=20, verbose_name='Objetivo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('is_active_member', models.BooleanField(default=True, verbose_name='Miembro activo')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Foto')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de cliente',
                'verbose_name_plural': 'Perfiles de clientes',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
