# Generated by Django 5.2.11 on 2026-02-20 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('specialty', models.CharField(choices=[('crossfit', 'CrossFit'), ('hiit', 'HIIT'), ('yoga', 'Yoga'), ('fuerza', 'Fuerza'), ('cardio', 'Cardio'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Especialidad')),
                ('bio', models.TextField(blank=True, verbose_name='Biografía')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='trainers/', verbose_name='Foto')),
                ('joined_at', models.DateField(auto_now_add=True, verbose_name='Incorporación')),
                ('user', models.OneToOneField(limit_choices_to={'is_staff': True, 'is_superuser': False}, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de entrenador',
                'verbose_name_plural': 'Perfiles de entrenadores',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
