# Generated by Django 5.2.11 on 2026-02-20 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('default_duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Duración por defecto (min)')),
                ('color', models.CharField(default='#0d6efd', max_length=7, verbose_name='Color (hex)')),
            ],
            options={
                'verbose_name': 'Tipo de clase',
                'verbose_name_plural': 'Tipos de clase',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GymClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='Inicio')),
                ('end_datetime', models.DateTimeField(verbose_name='Fin')),
                ('capacity', models.PositiveIntegerField(default=10, verbose_name='Aforo máximo')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Ubicación')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Cancelada')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('class_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='schedule.classtype', verbose_name='Tipo de clase')),
                ('instructor', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_classes', to=settings.AUTH_USER_MODEL, verbose_name='Instructor')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('waitlisted', 'Lista de espera'), ('attended', 'Asistió'), ('no_show', 'No se presentó')], default='confirmed', max_length=15, verbose_name='Estado')),
                ('booked_at', models.DateTimeField(auto_now_add=True, verbose_name='Reservado el')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelado el')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('gym_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='schedule.gymclass', verbose_name='Clase')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-booked_at'],
                'unique_together': {('client', 'gym_class')},
            },
        ),
    ]
